ame: FirstName



on: 

 push:

  branches:

   - 'main'

  

 workflow_dispatch: # manual way of starting workflows

  

 schedule:

  - cron: '10 * * * *'

  

jobs:

 first-job:

  runs-on: ubuntu-latest

  steps:

   - name: Simple shell command step 

    run: |

     echo Hello from Step 1

     echo Hello from Step 2

    

    

   - name: Another simple shell command step 

    run: echo Hello from Step 2

     

 second-job:

  runs-on: ubuntu-latest

  steps:

   - name: Simple shell command step 

    run: echo Hello 

     

 third-job:

  runs-on: ubuntu-latest

  needs: [second-job]

  steps:

   - name: Simple shell command step 

    run: echo Hello 

     

 dump_contexts_to_log:

  runs-on: ubuntu-latest

  steps:

   - name: Dump GitHub context

    id: github_context_step

    run: echo '${{ toJSON(github) }}'

   - name: Dump job context

    run: echo '${{ toJSON(job) }}'

   - name: Dump steps context

    run: echo '${{ toJSON(steps) }}'

   - name: Dump runner context

    run: echo '${{ toJSON(runner) }}'

   - name: Dump strategy context

    run: echo '${{ toJSON(strategy) }}'

   - name: Dump matrix context

    run: echo '${{ toJSON(matrix) }}'
