name: Issue Bugger



on:

 issues:

  types:

   - opened

permissions: write-all

jobs:

 label_issue:

  runs-on: ubuntu-latest

  steps:
   - env:

     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     ISSUE_URL: ${{ github.event.issue.html_url }}

    run: |

     gh issue edit $ISSUE_URL --add-label "bug"  
